# Generated by Django 2.2.4 on 2019-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Name',
            fields=[
                ('unique', models.CharField(max_length=200, primary_key=1, serialize=False, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
